apiVersion: v1
kind: Pod
metadata: 
  name: app
spec:
  containers:
    - name: app
      image: kodekloud/event-simulator
    - name: sidecar
      image: kodekloud/filebeat-configured
      volumeMounts:
      - name: log-volume
        mountPath: /var/log/event-simulator/
        